# Generated by Django 4.2.5 on 2023-11-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'запись блога', 'verbose_name_plural': 'запись блога'},
        ),
    ]
