# Generated by Django 4.2.5 on 2023-12-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'публикация', 'verbose_name_plural': 'публикации'},
        ),
    ]
