# Generated by Django 4.2.5 on 2023-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
