# Generated by Django 4.2.5 on 2023-12-24 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_version_name_alter_version_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(max_length=100, verbose_name='Наименование версии'),
        ),
    ]
